/*class ThriftyHealth : Health 
{
	Override void PostBeginPlay()
	{
		if(bDROPPED && ACS_ScriptCall("CVarCheck",1))
			bWALLSPRITE = TRUE;
		A_SetAngle(Random(0,360));
	Super.PostBeginPlay();
	}
	Override void Tick()
	{
		if(isFrozen())
			return;
		if(bDROPPED && ACS_ScriptCall("CVarCheck",1))
		{
			bWALLSPRITE = TRUE;
			self.angle += fRandom(3.0,4.0);
		}
		else
			bWALLSPRITE = FALSE;
		Super.Tick();
	}
}*/