class skp_PlasmaOffer : SwitchableDecoration 
{
	int user_amount;
	bool user_DontTransSpecial;
	int OldSpecial;
	Default
	{
		//$Category Weapons
		+SOLID;
		+USESPECIAL;
		Activation THINGSPEC_Deactivate;
		Radius 16;
		Height 44;
		DropItem "PlasmaRifle";
	}
	override void PostBeginPlay()
	{
		if(special && !user_DontTransSpecial)
			OldSpecial = special;
		special = 0;
	}
	States
	{
	Spawn:
	Active:
		WPRF B 1;
		Loop;
	Inactive:
		WPRF C -1
		{
			let yergun = A_DropItem(GetDropItems().Name);
			A_StartSound("misc/toss");
			if(user_amount && weapon(yergun))
			{
				weapon(yergun).AmmoGive1 = user_amount;
				yergun.special = self.OldSpecial;
				for(int i = 0; i < 5; i++)
					yergun.args[i] = self.args[i];
			}
			bUSESPECIAL = FALSE;
			bSOLID = FALSE;
		}
		Stop;
	}
}

class skp_IncOffer : skp_PlasmaOffer 
{
	Default
	{
		DropItem "skp_Incinerator";
	}
	States
	{
	Spawn:
	Active:
		WPRF D 1;
		Loop;
	}
}