class skp_PickupFlash : PickupFlash replaces PickupFlash
{
	Default
	{
		+NOGRAVITY
		+FORCEXYBILLBOARD
	}
	States
	{
	Spawn:
		IFOG ABABCDE 3 BRIGHT;
		Stop;
	}
	Override void PostBeginPlay()
	{
		bROLLSPRITE = Cvar.FindCVar("arg_GoreRotation").GetBool() ? TRUE : FALSE;
		bROLLCENTER = bROLLSPRITE;
		Self.Roll  += bROLLSPRITE ? Random(0,360) : 0;
		A_SetTranslucent(666,2);
		Super.PostBeginPlay();
	}
} 
