class skp_ExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel
{
	Default
	{
		+EXTREMEDEATH
		+DROPOFF
	}
	States
	{
	Death:
		BEXP A 5 BRIGHT;
		BEXP B 5 BRIGHT A_Scream;
		BEXP C 5 BRIGHT;
		BEXP D 5 BRIGHT
		{
			A_Explode();
			A_QuakeEx(1,1,1,60,0,128,"",0,0,0,0,96);
			A_SpawnItemEx("RocketSmokeTrail",0,0,2*(height/3),0,0,fRandom(1,2));
		}
		BEXP E 5 BRIGHT A_SpawnItemEx("RocketSmokeTrail",0,0,2*(height/3),0,0,fRandom(1,2));
		BEXP F 4 BRIGHT;
		BEXP G 3 BRIGHT;
		TNT1 A 1050 BRIGHT A_BarrelDestroy;
		TNT1 A 5 A_Respawn;
		Wait;
	}
	Override void Tick()
	{
		int t = 3;//all this does is randomize a bit which tic the effect happens on, that way if several of these are placed next to eachother they don't look so uniform
		int r = random(0,t-1);
		if((level.totaltime + r) % t == 0)//this spawns a particle every 3 tics with a random offset
		{
			A_SpawnParticle("439337",0,Random(25,35)/2,Random(1,3),0,random(1,-1)*random(0,Radius-6),random(1,-1)*random(0,Radius-6),Height-fRandom(8,12),0,0,fRandom(0.125,1),0,0,fRandom(-0.125,-0.25),fRandom(0.75,0.25));
		}
		Super.Tick();
	}
}
