class GoreNest : ExplosiveBarrel
{
	Default
	{
		Health 200;
		Radius 40;
		Height 92;
		-NOBLOOD
		+DONTTHRUST
		BloodColor "blue";
		DeathSound "world/barrelx";
 		Obituary "How did the gore nest eeven kill you?";
		Tag "Gore Nest";

		Dropitem "$vend_gorenest", VEND_DESC;
	}
	States
	{
	Spawn:
		GNST A -1;
		Loop;
	Death:
		GNST B 3 A_SpawnItemEx("blood",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
		GNST CD 3 BRIGHT
		{
			A_SpawnItemEx("skp_PlacedXdeathGib",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
			for(int i = 0; i < 2; i++)
			{
				A_SpawnItemEx("GoreNestExplosion",random(self.radius*1.5,self.radius*-1.5) ,random(self.radius*1.5,self.radius*-1.5) ,random(self.height/2,self.height-8));
			}
		}
		GNST E 3 BRIGHT
		{
			A_ScreamAndUnblock();
			for(int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("skp_PlacedXdeathGib",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
			}
			for(int i = 0; i < 2; i++)
			{
				A_SpawnItemEx("skp_GoreNestGib2",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_ABSOLUTEVELOCITY);
			}
			for(int i = 0; i < 5; i++)
			{
				A_SpawnItemEx("blood",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
			}
			for(int i = 0; i < 2; i++)
			{
				A_SpawnItemEx("GoreNestExplosion",random(self.radius*1.5,self.radius*-1.5) ,random(self.radius*1.5,self.radius*-1.5) ,random(self.height/2,self.height-8));
			}
		}
		GNST F 3 BRIGHT
		{
			for(int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("skp_PlacedXdeathGib",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_ABSOLUTEVELOCITY);
			}
			for(int i = 0; i < 2; i++)
			{
				A_SpawnItemEx("skp_GoreNestGib2",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_ABSOLUTEVELOCITY);
			}
			for(int i = 0; i < 5; i++)
			{
				A_SpawnItemEx("blood",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
			}
			for(int i = 0; i < 2; i++)
			{
				A_SpawnItemEx("GoreNestExplosion",random(self.radius*1.5,self.radius*-1.5) ,random(self.radius*1.5,self.radius*-1.5) ,random(self.height*0.6,self.height*1.3));
			}
		}
		
		GNST G 5 BRIGHT A_SpawnItemEx("skp_PlacedXdeathGib",0,0,45,frandom(-8,8),frandom(-8,8),frandom(3,8),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
		GNST HI 4 BRIGHT;
		GNST J -1;
		Wait;
	}
	Override Void PostBeginPlay()
	{
		for(int i = 0; i < 15; i++)
		{
			A_SpawnItemEx("skp_PlacedXdeathGib",0,0,45,frandom(-6,6),frandom(-6,6),frandom(3,6),random(0,360),SXF_USEBLOODCOLOR|SXF_ABSOLUTEVELOCITY);
			
		}
		Super.PostBeginPlay();
	}
}

class skp_GoreNestGib2 : skp_PlacedXdeathGib
{
	States
	{
		Spawn:
			XNST "#" 1;
			Loop;
		Death:
			XNST "#" -1 A_SpawnItemEx("skp_BloodSpurt",0,0,0,0.2*random(-10,10),0.2*random(-10,10),0.3*random(5,15),0, SXF_TRANSFERRENDERSTYLE|SXF_TRANSFERTRANSLATION|SXF_CLIENTSIDE,192);
			Stop;
	}
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		Frame = Random(7,8);
	}
}

class GoreNestExplosion : actor
{
	Default
	{
		+NOGRAVITY; +NOINTERACTION; +NOBLOCKMAP; +BRIGHT;
		renderstyle "Translucent";
		alpha 0.75;
	}
	States
	{
		Spawn:
			GXPL A 4;
			GXPL BCDEF 3;
		Stop;
	}
	Override void PostBeginPlay()
	{
		bXFLIP = Random(true,false);
		bYFLIP = Random(true,false);
		super.PostBeginPlay();
	}
}